name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image and push
      uses: docker/buid-push-action@v4
      with:
        context: .
        push: true
        tags: palandeta/isa-abr25-cicd-docker:flaskapp

    - name: Deploy to Docker (Installed in Ec2)
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker image pull palandeta/isa-abr25-cicd-docker:flaskpp
          docker container stop flask
          docker container rm flask
          docker container run -d --name flask -p 80:5000 palandeta/isa-abr25-cicd-docker:flaskpp
        
